set(CMAKE_SYSTEM_NAME QNX)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_C_FLAGS_INIT "-D_QNX_SOURCE")
set(CMAKE_CXX_FLAGS_INIT "-D_QNX_SOURCE")

if(NOT DEFINED ENV{QNX_HOST} OR NOT DEFINED ENV{QNX_TARGET})
  message(FATAL_ERROR "Run this build from a QNX SDP 8.0 environment")
endif()

set(QNX_HOST "$ENV{QNX_HOST}")
set(QNX_TARGET "$ENV{QNX_TARGET}")
set(CMAKE_SYSROOT "${QNX_TARGET}")

find_program(CMAKE_C_COMPILER aarch64-unknown-nto-qnx8.0.0-gcc
  PATHS "${QNX_HOST}/usr/bin" NO_DEFAULT_PATH REQUIRED)
find_program(CMAKE_CXX_COMPILER aarch64-unknown-nto-qnx8.0.0-g++
  PATHS "${QNX_HOST}/usr/bin" NO_DEFAULT_PATH REQUIRED)
find_program(CMAKE_AR aarch64-unknown-nto-qnx8.0.0-ar
  PATHS "${QNX_HOST}/usr/bin" NO_DEFAULT_PATH REQUIRED)
find_program(CMAKE_RANLIB aarch64-unknown-nto-qnx8.0.0-ranlib
  PATHS "${QNX_HOST}/usr/bin" NO_DEFAULT_PATH REQUIRED)
find_program(CMAKE_STRIP aarch64-unknown-nto-qnx8.0.0-strip
  PATHS "${QNX_HOST}/usr/bin" NO_DEFAULT_PATH REQUIRED)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
